version: 2


build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
    - pip install numpy
    
conda:
  environment: .environment.yml  

sphinx:
  configuration: docs/conf.py
